import{f as u}from"./app-florian.js";import{d as n,e as c}from"./app-bausteine.js";import{d as i,B as r,C as t,a as l,b as e,e as s,z as f}from"./app-vendor.js";import{_ as p}from"./app-quiz.js";const m=i({__name:"Nachhilfeangebot",setup(o){return(d,a)=>(l(),r(n,{id:"nachhilfeangebot",titel:"Mon offre de tutorat"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-12","data-aos":"fade-left","data-aos-delay":"100"},[e("p",null,`Tu as besoin d'aide en maths, physique, informatique ou ingénierie pour tes études ? Ou
          en français ou en allemand pour l'école ? Alors je peux certainement vous aider en tant que
          Master de mathématiques et d'informatique avec mention très bien, avec mon diplôme
          d'enseignant en
          physique, avec mon expérience professionnelle d'un an en tant que développeur de logiciels
          et en tant que tuteur de longue date de nombreux cours de mathématiques au LMU à Munich .
        `),s(),e("p",null,`Peu importe que tu fasses tes études en mathématiques, physique ou informatique en tant que
          matière principale ou secondaire et que tu aies besoin d'aide pour résoudre des problèmes de
          preuve ou d'arithmétique. Dès que tu m'as envoyé suffisamment de tâches pour une séance de
          tutorat à imelflorianingerl@gmail.com, nous pouvons prendre rendez-vous.`),s(),e("p",null,`Toutes les autres conditions pour le tutorat, telles que les sujets possibles, la prise de
          rendez-vous, la technologie pour le tutorat en ligne, les prix et les conditions
          d'annulation sont plus bas sur le site.`)])],-1)])]),_:1}))}}),h=i({__name:"MatheUni",setup(o){return(d,a)=>(l(),r(n,{id:"matheuni",titel:"Mathématique"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/ConvexeFrancais.jpg",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`Tu sais calculer, mais tu ne sais pas démontrer quoi que ce soit. Dans un cours particulier,
          nous pouvons faire les deux choses.`),s(),e("p",null,[s(`
          Voilà une liste de matières en lesquelles je m'y connais:
          Algèbre Linéare 1+2 (`),e("a",{href:"Pdfs/LinAlgFranz/Soutien Olivois 16.5.2022.pdf"},"1"),s(","),e("a",{href:"Pdfs/LinAlgFranz/Soutien Olivois 18.5.2022.pdf"},"2"),s(", "),e("a",{href:"Pdfs/LinAlgFranz/Soutien Olivois 19.5.2022.pdf"},"3"),s(" , "),e("a",{href:"Pdfs/LinAlg/LinAlg4.pdf"},"4"),s(`), Analyse 1
          (`),e("a",{href:"Pdfs/Ana1Franz/Cours de soutien Eyana 29.9.2023.pdf"},"1"),s(","),e("a",{href:"Pdfs/Ana1Franz/Soutien Edwin 2.8.2022.pdf"},"2"),s(", "),e("a",{href:"Pdfs/Ana1Franz/Soutien Edwin 23.7.2022.pdf"},"3"),s(`,
          `),e("a",{href:"Pdfs/Ana1Franz/Soutien Edwin 30.7.2022.pdf"},"4"),s(", "),e("a",{href:"Pdfs/Ana1/Ana4.pdf"},"4"),s(`),
          Analyse 2 (`),e("a",{href:"Pdfs/Ana2/ana21.pdf"},"1"),s(","),e("a",{href:"Pdfs/Ana2/ana22.pdf"},"2"),s(`,
          `),e("a",{href:"Pdfs/Ana2/ana23.pdf"},"3"),s(", "),e("a",{href:"Pdfs/Ana2/ana24.pdf"},"4"),s(", "),e("a",{href:"Pdfs/Ana2/ana25.pdf"},"5"),s(`),
          Théorie de la mésure et probabilité (`),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 12.1.2024.pdf"},"1"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 2.1.2024.pdf"},"2"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 15.12.2023.pdf"},"3"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leiticia 4.1.2023.pdf"},"4"),s(","),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leiticia 5.1.2023.pdf"},"5"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 13.1.2024.pdf"},"6"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 14.1.2024.pdf"},"7"),s(". "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 6.1.2023.pdf"},"8"),s("), Numérique 1+2 ("),e("a",{href:"Pdfs/Numerik/Numerik1.pdf"},"1"),s(", "),e("a",{href:"Pdfs/Numerik/Numerik2.pdf"},"2"),s(", "),e("a",{href:"Pdfs/Numerik/Numerik3.pdf"},"3"),s(", "),e("a",{href:"Pdfs/Numerik/Numerik4.pdf"},"4"),s(`),
          Stochastique (
          `),e("a",{href:"Pdfs/ProbaFranz/Soutien Edwin 8.7.2022.pdf"},"1"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 2.1.2024.pdf"},"2"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 15.12.2023.pdf"},"3"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leiticia 4.1.2023.pdf"},"4"),s(","),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leiticia 5.1.2023.pdf"},"5"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 13.1.2024.pdf"},"6"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 14.1.2024.pdf"},"7"),s(". "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 6.1.2023.pdf"},"8"),s("), Analyse Complexe 1+2 ("),e("a",{href:"Pdfs/Funktionentheorie/FT1.pdf"},"1"),s(", "),e("a",{href:"Pdfs/Funktionentheorie/FT2.pdf"},"2"),s(" ), Équations Différentielles ("),e("a",{href:"Pdfs/DiffglenFranz/Cours de soutien Melina 11.11.2023.pdf"},"1"),s(","),e("a",{href:"Pdfs/DiffglenFranz/Soutien Edwin 30.7.2022.pdf"},"2"),s(`,
          `),e("a",{href:"Pdfs/Diffglen/ODE2.pdf"},"3"),s(", "),e("a",{href:"Pdfs/Diffglen/ODE3.pdf"},"4"),s(", "),e("a",{href:"Pdfs/Diffglen/ODE4.pdf"},"4"),s(", "),e("a",{href:"Pdfs/Diffglen/ODE5.pdf"},"5"),s(`), Équations
          aux Dérivées Partielles (`),e("a",{href:"Pdfs/PartielleDGLs/Nachhilfe Eren 22.2.2022.pdf"},"1"),s(", "),e("a",{href:"Pdfs/PartielleDGLs/Nachhilfe Guo 28.8.2022.pdf"},"2"),s(` ),
          Théorie de la Probabilité ( `),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 12.1.2024.pdf"},"1"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 2.1.2024.pdf"},"2"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 15.12.2023.pdf"},"3"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leiticia 4.1.2023.pdf"},"4"),s(","),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leiticia 5.1.2023.pdf"},"5"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 13.1.2024.pdf"},"6"),s(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 14.1.2024.pdf"},"7"),s(". "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 6.1.2023.pdf"},"8"),s(`),
          algèbre (`),e("a",{href:"Pdfs/Algebra/Algebra1.pdf"},"1"),s(", "),e("a",{href:"Pdfs/Algebra/Algebra2.pdf"},"2"),s(", "),e("a",{href:"Pdfs/Algebra/Algebra3.pdf"},"3"),s(", "),e("a",{href:"Pdfs/Algebra/Algebra4.pdf"},"4"),s(", "),e("a",{href:"Pdfs/Algebra/Algebra5.pdf"},"5"),s(", "),e("a",{href:"Pdfs/Algebra/Algebra6.pdf"},"6"),s("), logique ("),e("a",{href:"Pdfs/LogikFranz/Soutien Edwin 2.8.2022.pdf"},"1"),s(", "),e("a",{href:"Pdfs/Logik/Logik2.pdf"},"2"),s(", "),e("a",{href:"Pdfs/Logik/Logik3.pdf"},"3"),s(", "),e("a",{href:"Pdfs/Logik/Logik4.pdf"},"4"),s("), optimisation ("),e("a",{href:"Pdfs/Optimierung/Optimierung1.pdf"},"1"),s(","),e("a",{href:"Pdfs/Optimierung/Optimierung2.pdf"},"2"),s(`), processus stochastiques, statistiques
          (`),e("a",{href:"Pdfs/Statistik/Statistik1.pdf"},"1"),s(`,
          `),e("a",{href:"Pdfs/Statistik/Statistik2.pdf"},"2"),s(", "),e("a",{href:"Pdfs/Statistik/Statistik3.pdf"},"3"),s(", "),e("a",{href:"Pdfs/Statistik/Statistik4.pdf"},"4"),s("), Théorie des Graphs ("),e("a",{href:"Pdfs/Graphentheorie/GT1.pdf"},"1"),s("), Géométrie ("),e("a",{href:"Pdfs/Geometrie/Geo1.pdf"},"1"),s(`)
        `)])])],-1)])]),_:1}))}}),g=i({__name:"InfoUni",setup(o){return(d,a)=>(l(),r(n,{id:"infouni",titel:"Informatique"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/infouni2francais.jpg",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,"Tu as des problèmes avec la grammaire de l'informatique théorique? Je peux t'aider."),s(),e("p",null,[s(`
          Voilà une liste des matières en lesquelles je m'y connais: Théorie de Langages, Calculabiltié et Complexité(`),e("a",{href:"FormaleSprachenFranz/Soutien Edwin 9.8.2022 besser.pdf"},"1"),s(","),e("a",{href:"Pdfs/FormaleSprachen/FS2.pdf"},"2"),s(" , "),e("a",{href:"Pdfs/FormaleSprachen/FS3.pdf"},"3"),s(", "),e("a",{href:"Pdfs/FormaleSprachen/FS4.pdf"},"4"),s(`,
          `),e("a",{href:"Pdfs/PumpingEigenschaft.pdf"},"5"),s("), Introduction à l'Informatique Théoretique ("),e("a",{href:"Pdfs/TheoretischeInformatik/TH1.pdf"},"1"),s(", "),e("a",{href:"Pdfs/TheoretischeInformatik/TH2.pdf"},"2"),s(", "),e("a",{href:"Pdfs/TheoretischeInformatik/TH3.pdf"},"3"),s(", "),e("a",{href:"Pdfs/TheoretischeInformatik/TH4.pdf"},"4"),s(", "),e("a",{href:"Pdfs/TheoretischeInformatik/TH5.pdf"},"5"),s(`), Structures de Données et Algorithmes
          (`),e("a",{href:"Pdfs/Ana1Franz/Cours de soutien Eyana 29.9.2023.pdf"},"1"),s(", "),e("a",{href:"Pdfs/AlgoDat/AlgoDat1.pdf"},"2"),s(", "),e("a",{href:"Pdfs/AlgoDat/AlgoDat2.pdf"},"3"),s(", "),e("a",{href:"Pdfs/AlgoDat/AlgoDat3.pdf"},"4"),s(", "),e("a",{href:"Pdfs/AlgoDat/AlgoDat4.pdf"},"5"),s(", "),e("a",{href:"Pdfs/AlgoDat/AlgoDat5.pdf"},"6"),s(", "),e("a",{href:"Pdfs/AlgoDat/AlgoDat6.pdf"},"7"),s(`),
          Théorie de la Complexité ( `),e("a",{href:"Pdfs/Komplexitaetstheorie/Komplexitaet1.pdf"},"1"),s(`),
          Introduction à la Programmation (`),e("a",{href:"Pdfs/Programmierung/ListUndStack.pdf"},"1"),s(","),e("a",{href:"Pdfs/LineareListe.pdf"},"2"),s(", "),e("a",{href:"Pdfs/Programmierung/Programmierung2.pdf"},"3"),s(`),
          Programmation Fonctionelle avec Haskell (`),e("a",{href:"Pdfs/Haskell/Nachhilfe Marvin 15.6.2022.pdf"},"1"),s(","),e("a",{href:"Pdfs/Haskell/Nachhilfe Marvin 17.6.2022.pdf"},"2"),s(", "),e("a",{href:"Pdfs/Haskell/Nachhilfe Nissa 2.7.2022.pdf"},"3"),s("), Structures Discrètes ("),e("a",{href:"Pdfs/DiskreteStrukturen/Diskret1.pdf"},"1"),s(", "),e("a",{href:"Pdfs/DiskreteStrukturen/Diskret2.pdf"},"2"),s(", "),e("a",{href:"Pdfs/DiskreteStrukturen/Diskret3.pdf"},"3"),s(", "),e("a",{href:"Pdfs/DiskreteStrukturen/Diskret4.pdf"},"4"),s("), Logique pour les Informaticiens ("),e("a",{href:"Pdfs/Logik/Logik5.pdf"},"1"),s(`),
          Informatique Graphique (`),e("a",{href:"Pdfs/Computergraphik/graphik1.png"},"1"),s(`,
          `),e("a",{href:"Pdfs/Computergraphik/graphik2.png"},"2"),s(`)
        `)]),e("p")])],-1),s(),e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/programming.png",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,[s(`
          Aussi, je peux t'aider bien avec la programmation (Java, C/C++, C#, Haskell, R, Python,
          Prolog, Rust, OCaml) ou avec la programmation du web
          (Html, CSS,
          JavaScript, PHP,SQL, NodeJS, VueJS, AngularJS, MongoDB, Java Servlets/JSP). Nous utiliserions Eclipse, IntelliJ ou
          VisualStudio comme environnement de développement avec le
          `),e("a",{href:"https://plugins.jetbrains.com/plugin/14225-codetogether"},"CodeTogether-Plugin"),s(`
          , qui permet Pair-Programming.
        `)])])],-1)])]),_:1}))}}),P=i({__name:"PhysikUni",setup(o){return(d,a)=>(l(),r(n,{id:"physikuni",titel:"Physique"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/physikuni.png",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`Comme un bon physicien, ton nombre d'erreus de signes doit toujours être pair. Je peux
          t'expliquer tout le reste.`),s(),e("p",null,[s(`
          Dans un cours particulier, on peux faire: Physique éxperimentale, ça veut dire
          Mécanique (`),e("a",{href:"Pdfs/Mechanik/M1.pdf"},"1"),s(", "),e("a",{href:"Pdfs/Mechanik/M2.pdf"},"2"),s(", "),e("a",{href:"Pdfs/Mechanik/M3.pdf"},"3"),s(", "),e("a",{href:"Pdfs/Mechanik/Nachhilfe Ksenija 1.12.2021.pdf"},"4"),s(", "),e("a",{href:"Pdfs/Mechanik/Nachhilfe Steven 9.5.2021.pdf"},"5"),s(`),
          Électromagnétisme (`),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Nick 5.5.2021.pdf"},"1"),s(`,
          `),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Suganya 21.9.2021.pdf"},"2"),s(`,
          `),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Suganya 22.9.2021.pdf"},"3"),s(`,
          `),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Nick 5.7.2021.pdf"},"4"),s(`,
          `),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Shir 4.7.2021.pdf"},"5"),s(`,
          `),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Shir 11.7.2021.pdf"},"6"),s(`,
          `),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Shir 16.6.2021.pdf"},"7"),s(`),
          Vagues électromagnetiques et Optique (`),e("a",{href:"Pdfs/WellenUndOptik/Optik1.pdf"},"1"),s(","),e("a",{href:"Pdfs/WellenUndOptik/Optik2.pdf"},"2"),s(", "),e("a",{href:"Pdfs/WellenUndOptik/Optik3.pdf"},"3"),s(", "),e("a",{href:"Pdfs/WellenUndOptik/Optik4.pdf"},"4"),s(","),e("a",{href:"Pdfs/WellenUndOptik/Optik5.pdf"},"5"),s(","),e("a",{href:"Pdfs/WellenUndOptik/Nachhilfe Tuba 2.12.2021.pdf"},"6"),s(`),
          Thermodynamique/Physique Statistique(`),e("a",{href:"Pdfs/ThermodynamikFranz/Cours de soutien Thomas 16.9.2023.pdf"},"1"),s(","),e("a",{href:"Pdfs/ThermodynamikFranz/Cours de soutien Thomas 17.9.2023.pdf"},"2"),s(","),e("a",{href:"Pdfs/ThermodynamikFranz/Cours de soutien Thomas 24.9.2023.pdf"},"3"),s(`), Théorie de la Relativité, Physique Atomique, Physique Nucléaire et
          Physique du Solide (`),e("a",{href:"Pdfs/Festkörperphysik/Nachhilfe Suganya 20.9.2021.pdf"},"1"),s(`)

          et `),e("br"),s(` Physique Théorique, ça veut dire Mecanique Théorétique,
          Électrodynamique (`),e("a",{href:"Pdfs/Elektrodynamik/ED1.pdf"},"1"),s(", "),e("a",{href:"Pdfs/Elektrodynamik/Nachhilfe Nick 31.5.2021.pdf"},"2"),s(`),
          Mécanique Quantique (`),e("a",{href:"Pdfs/QM/QM1.pdf"},"1"),s(", "),e("a",{href:"Pdfs/QM/QM2.pdf"},"2"),s(", "),e("a",{href:"Pdfs/QM/QM3.pdf"},"3"),s(", "),e("a",{href:"Pdfs/QM/QM4.pdf"},"4"),s(`) et Thermodynamique
          (`),e("a",{href:"Pdfs/Thermodynamik/TD1.pdf"},"1"),s(", "),e("a",{href:"Pdfs/Thermodynamik/TD2.pdf"},"2"),s(`) et
          `),e("br"),s(" pour les ingénieurs Mécanique appliquée ("),e("a",{href:"Pdfs/TechnischeMechanik/Nachhilfe Balbine 15.12.2021.pdf"},"1"),s(`,
          `),e("a",{href:"Pdfs/TechnischeMechanik/Nachhilfe Hicham 31.12.2021.pdf"},"2"),s(`)
          et Mécanique des fluides (`),e("a",{href:"Pdfs/Strömungslehre/SL1.pdf"},"1"),s(`,
          `),e("a",{href:"Pdfs/Strömungslehre/Nachhilfe Gwendolin 30.10.2021.pdf"},"2"),s(", "),e("a",{href:"Pdfs/Strömungslehre/Nachhilfe Wei Liu 27.3.2022.pdf"},"3"),s(`)

        `)])])],-1)])]),_:1}))}}),v=i({__name:"Ingenieurwesen",setup(o){return(d,a)=>(l(),r(n,{id:"ingenieurwesen",titel:"Science d'ingénieur"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/ingenieurwesen.png",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`Quand j'étais aux États-Unis il y a quelques années, je me suis rendu compte que
          "German Engineering" est admiré là-bas.`),s(),e("p",null,[s(`
          Dans un cours de soutien, nous pouvons faire: Mécanique (`),e("a",{href:"Pdfs/TechnischeMechanik/Nachhilfe Balbine 15.12.2021.pdf"},"1"),s(`,
          `),e("a",{href:"Pdfs/TechnischeMechanik/Nachhilfe Hicham 31.12.2021.pdf"},"2"),s(`),
          Électrotecnique (`),e("a",{href:"Pdfs/Elektrotechnik/Nachhilfe Raphael 26.10.2022.pdf"},"1"),s(", "),e("a",{href:"Pdfs/Elektrotechnik/Nachhilfe Shir 4.7.2021.pdf"},"2"),s(", "),e("a",{href:"Pdfs/Elektrotechnik/Nachhilfe Shir 11.7.2021.pdf"},"3"),s(`)
          and Mécanique des Fluides (`),e("a",{href:"Pdfs/Strömungslehre/SL1.pdf"},"1"),s(`,
          `),e("a",{href:"Pdfs/Strömungslehre/Nachhilfe Gwendolin 30.10.2021.pdf"},"2"),s(`,
          `),e("a",{href:"Pdfs/Strömungslehre/Nachhilfe Wei Liu 27.3.2022.pdf"},"3"),s(`)
          

        `)])])],-1)])]),_:1}))}}),_=i({__name:"MatheSchule",setup(o){return(d,a)=>(l(),r(n,{id:"matheschule",titel:"Mathématique"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/matheschule.png",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`En mathématiques, la seule chose à faire est de trouver la bonne équation et puis de la
          résoudre
          sans se tromper dans son calcul.`)])],-1)])]),_:1}))}}),b=i({__name:"PhysikSchule",setup(o){return(d,a)=>(l(),r(n,{id:"physikschule",titel:"Physique"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/physiqueecole.jpg",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,"N'aie pas peur de la physique. Seulement avec la formule F=ma, vous irez déja assez loin.")])],-1)])]),_:1}))}}),q=i({__name:"InfoSchule",setup(o){return(d,a)=>(l(),r(n,{id:"infoschule",titel:"Informatique"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/infoschule.jpg",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`Un ordinateur ne peut pas sentir et il ne peut pas penser lui-même, mais il peut trier des
          choses très rapidement.
          C'est donc utile dans la vie de savoir qu'une souris d'ordinateur ne morde pas.`)])],-1)])]),_:1}))}}),k=i({__name:"Deutsch",setup(o){return(d,a)=>(l(),r(n,{id:"deutsch",titel:"Allemand"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/deutsch.png",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`Deutsche Sprache = Schwere Sprache. Ich kann dir erklären, wie du die ä's, ö's und ü's richtig verteilen musst,
          damit man dich noch besser versteht.
        `),s(`
        Ça veut dire: Je peux t'expliquer comment tu dois distribuer tous les ä, ö et ü afin qu'on te comprenne mieux.

      `)])],-1)])]),_:1}))}}),y=i({__name:"Englisch",setup(o){return(d,a)=>(l(),r(n,{id:"englisch",titel:"Anglais"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/FlyerConditionalSentences.jpg",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`You've got the nose full of English? Ne dites pas ça! Dites plutôt "I'm fed up with
          English" et venez chez moi pour un cours particulier.`)])],-1)])]),_:1}))}}),S={class:"row"},z={class:"col-lg-8 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},x={id:"nutritionquiz"},A=i({__name:"Ernaehrung",setup(o){return(d,a)=>(l(),r(n,{id:"ernaehrung",titel:"Nourriture"},{default:t(()=>[e("div",S,[e("div",z,[e("div",x,[f(p,{quiz:"nutrition",lg:"fr"})])]),a[0]||(a[0]=s()),a[1]||(a[1]=e("div",{class:"col-lg-3 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`Mes élèves tombent souvent et soudainement malades, dans la plupart des cas 5 minutes
          avant un cours particulier. Donc, il y a un petit quiz à droite pour la nourriture saine.
        `)],-1))])]),_:1}))}}),C={class:"row"},M={class:"col-lg-8 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},T={id:"conciousness"},F=i({__name:"Bewusstsein",setup(o){return(d,a)=>(l(),r(n,{id:"bewusstsein",titel:"Conscience"},{default:t(()=>[e("div",C,[e("div",M,[e("div",T,[f(p,{quiz:"consciousness",lg:"fr"})])]),a[0]||(a[0]=s()),a[1]||(a[1]=e("div",{class:"col-lg-4 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,"La conscience devrait être une majeure à l'école mais elle ne l'est pas. ")],-1))])]),_:1}))}}),L={class:"row"},w={class:"col-lg-8 order-2 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},D=i({__name:"Schach",setup(o){return(d,a)=>(l(),r(n,{id:"schach",titel:"Échec"},{default:t(()=>[e("div",L,[e("div",w,[f(c,{lg:"fr"})]),a[0]||(a[0]=s()),a[1]||(a[1]=e("div",{class:"col-lg-4 pt-4 pt-lg-0 order-1 order-lg-1 content"},[e("p",null,`L'échec est bon pour la capacité d'imagination. Les problèmes à droite datent d'une époque
          pendant laquelle je
          donnais encore des cours d'échecs à l'école primaire.`)],-1))])]),_:1}))}}),N=i({__name:"WebsitenUndFlyer",setup(o){return(d,a)=>(l(),r(n,{id:"websitenundflyer",titel:"Websiten"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/WebsiteProgrammierungFlyer3.png",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`Besoin d'aide pour un projet de Programmation Web pour vos études?
          Ou souhaites-tu apprendre la Programmation Web pour créer ta propre site Web
          basé sur HTML, CSS et JavaScript et as-tu besoin d'aide pour démarrer?
          Alors je peux certainement t'aider avec mes connaissances et mon expérience
          dans les domaines suivants:
        `),s(),e("p"),e("ul",null,[e("li",null,"Programmation des Websites statiques/du frontend (Html, CSS, JavaScript, Bootstrap, VueJS, AngularJS)"),s(),e("li",null,"Programmatin des Websites dynamiques (PHP, NodeJS, Java Servlets /JSP)"),s(),e("li",null,"Base de données (MySQL, MongoDB)"),s(),e("li",null,"Responsive Web-Design"),s(),e("li",null,"Édition d'images (avec GIMP)"),s(),e("li",null,"Hébergement (par exemple gratuit sur GitHub )"),s(),e("li",null,"Légal"),s(),e("li",null,"Traduction (en Allemand et Anglais)")]),s(),e("p")])],-1)])]),_:1}))}}),E=i({__name:"Preise",setup(o){return(d,a)=>(l(),r(n,{id:"preise",titel:"Prix, rendez-vous et paiement"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-12 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("h3",null,"Prix"),s(),e("p",null,"4*25 euros pour 4*60 min de cours pour toi ou pour toi et un ami"),s(),e("p",null,"30 euros pour un seul cours de 60 min"),s(),e("p"),s(),e("p",null,[s(`
          Si le cours a duré plus que 60 minutes, il faut appliquer la formule:`),e("br"),s(` Prix = Temps / (60
          min) * (Prix pour 60 min)
        `)]),s(),e("p",null,`
          Tu peux obtenir le prix le moins cher pour un forfait de 4*60 minutes si tu as suffisamment d'exercices intéressants.
          Pour le forfait, il faut prendre au moins une heure de cours chaque semaine. Je suis disponible tous les jours de la semaine de 8h à 21h et peux t'aider dans de nombreuses matières.
          !!! Attention !!! Si pour une raison quelconque tu ne peux pas ou n'en ressens pas le besoin pendant une semaine,
          l'argent serait toujours dû. Sinon, les mêmes conditions d'annulations que ci-dessous s'appliquent à chacune des 4 rendez-vous d'un paquet.
        `),s(),e("h3",null,"Rendez-vous, paiement et conditions d'annulation"),s(`
        Je ne conviens de la première heure de cours que par mail. Je me tiens à disposition ensuite par Skype. Merci de suivre le processus de prise de rendez-vous suivant:

        `),e("ol",null,[e("li",null,"Tu m'envoies tes exercices et tes notes de cours."),s(),e("li",null,`Si je connais ce genre d'exercices, je te dirai que tu peux effectuer le paiement
            via
            Paypal avec l'option "Envoyer de l'argent à vos proches"* ou virement bancaire +
            Screenshot. Dans l'intitulé du virement, merci d'inscrire ton nom et tes préférences de
            rendez-vous, par exemple quelque chose comme "Tutorat en mathématiques Elif souhaité le
            mercredi 11.1 à partir de 15h jusqu'à 21h  ou le samedi 12.1 entre 8h et 12h ou dimanche toute la journée".
          `),e("li",null,`Après avoir reçu le paiement, je te donnerai une confirmation de rendez-vous selon
            tes préférences (si c'est possible) ou je te proposerai 2-3 rendez-vous pour les
            prochains jours`),s(),e("li",null,"Nous attendons avec impatience notre rencontre et tu peux m'envoyer des exercices/notes de cours manquants ou supplémentaires.")]),s(),e("p",null,[e("span",{style:{"font-weight":"bold"}},"!!!Attention aux conditions d'annulation, pas de report de rendez-vous!!!"),s(`
          Lors d'une annulation de rendez-vous (n'importe quand avant le cours) ou de problèmes techniques (par exemple une connection d'Internet instable, l'impossibilité d'utiliser Skype,Zoom,le microphone ou les haut-parleurs ) ou après un retard de plus de 10 minutes de ton côté, l'argent est quand-même dû et je ne suis plus tenu d'attendre.
        `)]),s(),e("p",null,`Lors d'une annulation ou une panne d'Internet de mon côté, tu recevras un autre rendez-vous
          ou ton
          argent.`),s(),e("p",null,`*Sans l'option "Envoyer de l'argent à vos proches", il y a 2 euros de frais pour Paypal.`)])],-1)])]),_:1}))}}),j=i({__name:"Tutorium",setup(o){return(d,a)=>(l(),r(n,{id:"tutorium",titel:"Cours particuliers en groupe"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/owllehrer.png",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p"),e("p",null,`Dans le cadre du tutoriel, tu bénéficieras également d'un soutien individuel pour vos exercices,
            car il y a un maximum de 5 étudiants présents. Si tu as seulement besoin d'approches/idées/conseils pour tes exercices
             dans certains endroits et que si tu souhaites bénéficier de l'énergie d'apprentissage d'un groupe, c'est idéal pour toi.`),s(),e("p",null,"Le tutoriel a actuellement lieu tous les jeudis de 19h à 20h."),s(),e("p",null,"Tu recevras un lien vers le Whiteboard Miro et un lien d'invitation à une réunion Teams de ma part par e-mail si tu es inscrit à l'avance."),s(),e("p",null,"Prix 10 euros / heure"),s(),e("p")])],-1)])]),_:1}))}}),O=i({__name:"MethodeEnseignement",setup(o){return(d,a)=>(l(),r(n,{id:"methodeenseignement",titel:"Méthode d'enseignement"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/owllehrer.png",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`
          Parmi les exercices que tu m’as envoyés, nous en choissisons les meilleurs. Pour expliquer,
          j’utilise des schémas, des mots , des formules, des
          règles générales et des théorèmes (de tes notes de cours), des couleurs, des exemples et
          enfin, l’exercice
          s’explique lui-même par sa solution et l’interpretation dans le contexte et la validation.
        `)])],-1)])]),_:1}))}}),$=i({__name:"Online",setup(o){return(d,a)=>(l(),r(n,{id:"online",titel:"Cours particulier en ligne"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/miroapp.png",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,[s(`
          Pour les cours particuliers en ligne, j'utilise Skype ou Zoom.
          Si vous préférez l'un ou l'autre, vous pouvez le mentionner. En plus, j'utilise le `),e("a",{href:"https://miro.com/online-whiteboard/"},"Miro-Online-Whiteboard"),s(`,
          avec lequel on peut écrire quelque chose ensemble. Un whiteboard plein est ici par exemple:
          `),e("a",{href:"Pdfs/Beispielwhiteboard.pdf"},"Exemple d'un whiteboard plein")])])],-1)])]),_:1}))}}),J=i({__name:"UeberMich",setup(o){return(d,a)=>(l(),r(n,{id:"uebermich",titel:"Sur moi"},{default:t(()=>[...a[0]||(a[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/me3.jpg",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("ul",{style:{"list-style-type":"disc"}},[e("li",null,`Master de mathématiques et informatique à l'université LMU de Munich avec mention très
            bien`),s(),e("li",null,`Tuteur pendant >5 année à l'université LMU à Munich pour beaucoup de cours mathématiques
            et physique`),s(),e("li",null,"Bac en anglais, allemand et français avec mention bien"),s(),e("li",null,`Expérience professionelle pendant une demie année comme prof de mathématiques et
            physique au Lycée Gröbenzell et Olching`),s(),e("li",null,"Depuis octobre 2010 prof particulier pour les étudiants"),s(),e("li",null,"Expérience professionelle pendant une année comme un ingénieur de software")])])],-1),s(),e("div",{class:"row",style:{"margin-top":"10px"}},[e("div",{class:"col-lg-2 order-1 order-lg-1","data-aos":"fade-right","data-aos-delay":"100"},[e("img",{src:"assets/img/yoga/kopfstand2.jpg",class:"img-fluid",alt:""})]),s(),e("div",{class:"col-lg-10 pt-4 pt-lg-0 order-2 order-lg-2 content"},[e("p",null,[s(`Je suis né en 1993, fils d'un ingénieur électricien et d'une nutritionniste. J'ai également
          été profondément influencé par mon grand-père, qui vivait en partie de légumes du potager et
          en partie de pissenlits afin de pouvoir transmettre plus d'argent à ses petits-enfants pour
          leurs études.`),e("br"),s(`
          J'ai aussi beaucoup appris de ma tante et de mon oncle, qui - parce qu'ils étaient
          professeurs d'histoire et de langues - avaient toujours beaucoup d'histoires amusantes à
          raconter.`),e("br"),s(`
          Je m'intéresse moi-même à tout ce qui touche aux maths, aux sciences, à la technologie, au
          langage et à la psychologie, cette dernière pour le plus grand plaisir de mon psychiatre qui
          fait fortune en m'écoutant.`),e("br"),s(`
          Avec tout ce qu'il est possible d'apprendre intellectuellement, je fais moi-même beaucoup de Yoga, sport et
          promenades en forêt pour compenser et je vous recommande cela comme préparation à un examen.
        `)])])],-1)])]),_:1}))}}),G={logo:"Demande à Florian!",knopf:"Écris-moi un message",heroBild:"assets/img/AnnonceMathsAvecLaTete.png",flaggen:u.flaggen,menue:[{titel:"Université",ziel:"#matheuni",eintraege:[{titel:"Mathématique",ziel:"#matheuni"},{titel:"Informatique",ziel:"#infouni"},{titel:"Physique",ziel:"#physikuni"},{titel:"Sciences d'ingénieur",ziel:"#ingenieurwesen"}]},{titel:"Lycée",ziel:"#matheschule",eintraege:[{titel:"Mathématique",ziel:"#matheschule"},{titel:"Physique",ziel:"#physikschule"},{titel:"Informatique",ziel:"#infoschule"},{titel:"Allemand",ziel:"#deutsch"},{titel:"Anglais",ziel:"#englisch"}]},{titel:"Vie",ziel:"#ernaehrung",eintraege:[{titel:"Nourriture",ziel:"#ernaehrung"},{titel:"Conscience",ziel:"#bewusstsein"},{titel:"Échec",ziel:"#schach"},{titel:"Websites",ziel:"#websitenundflyer"}]},{titel:"Prix et d'autres infos",ziel:"#preise",eintraege:[{titel:"Prix, rendez-vous et paiement",ziel:"#preise"},{titel:"Méthode d'enseignement",ziel:"#methodeenseignement"},{titel:"Cours particuliers en groupe",ziel:"#tutorium"},{titel:"Cours particuliers en ligne",ziel:"#online"}]},{titel:"Sur moi",ziel:"#uebermich",eintraege:[]}],kontakt:{karteHoehe:"200px",karte:u.karte,adresse:"Adresse:",email:"Email:",strasse:u.strasse,ort:u.ort,mailadresse:u.mailadresse,absatz:"Tu peux utiliser cette formulaire pour me contacter, mais il est préférable si tu me contactes via e-mail et si tu m'envoies assez d'exercices dont on peut parler pendant un cours particulier.",formular:{action:"https://api.web3forms.com/submit",accessKey:"aaa027db-e72d-41d2-9b3b-7603e4908475",weiterleitung:"https://florianingerl.github.io/formsubmissionconfirmation.html",botcheck:!0,name:"Ton nom",mail:"Ton Email",betreff:"Subject",nachricht:"Message",knopf:"Envoie-moi le message!"}},fuss:{telefon:"Téléphone:",telefonnummer:u.telefonnummer,mailadresse:u.mailadresse,sozial:!0},schach:"fr",abschnitte:[m,h,g,P,v,_,b,q,k,y,A,F,D,N,E,j,O,$,J]};export{G as default};
