import{f as c}from"./app-florian.js";import{d as r,e as p}from"./app-bausteine.js";import{d as i,B as n,C as o,a as t,b as e,e as a,z as f}from"./app-vendor.js";import{_ as u}from"./app-quiz.js";const m=i({__name:"Nachhilfeangebot",setup(l){return(d,s)=>(t(),n(r,{id:"nachhilfeangebot",titel:"Mi oferta de tutoría"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-12","data-aos":"fade-left","data-aos-delay":"100"},[e("p",null,`¿Necesitas ayuda con matemáticas, física, informática o ingeniería para tus estudios?
                  ¿O en francés o alemán para la escuela? Entonces seguramente puedo ayudarte como Máster en Matemáticas
                  e Informática con honores, con mi calificación docente en Física, con mi experiencia profesional
                  de un año como desarrollador de software y como tutor de muchos años de numerosos cursos de matemáticas
                  en la LMU en Múnich.
                `),a(),e("p",null,`No importa si estudias matemáticas, física o informática como especialidad o como segunda asignatura  y
      si necesitas ayuda para resolver problemas de demostración o aritméticos.
      Tan pronto como me hayas enviado suficientes tareas para una sesión de tutoría a imelflorianingerl@gmail.com,
      podremos programar una cita.
    `),a(),e("p",null,`Todos los demás términos y condiciones de tutoría, como posibles temas, programación, tecnología de tutoría en línea,
       precios y políticas de cancelación, se encuentran más abajo en el sitio web.
    `)])],-1)])]),_:1}))}}),h=i({__name:"MatheUni",setup(l){return(d,s)=>(t(),n(r,{id:"matheuni",titel:"Matemáticas"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/ConvexeFrancais.jpg",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,"Sabes calcular, pero no sabes demostrar nada. En una clase privada podemos hacer ambas cosas."),a(),e("p",null,[a(`
          Aquí hay una lista de temas sobre los que sé mucho:
          Álgebra Lineal 1+2 (`),e("a",{href:"Pdfs/LinAlgFranz/Soutien Olivois 16.5.2022.pdf"},"1"),a(","),e("a",{href:"Pdfs/LinAlgFranz/Soutien Olivois 18.5.2022.pdf"},"2"),a(", "),e("a",{href:"Pdfs/LinAlgFranz/Soutien Olivois 19.5.2022.pdf"},"3"),a(" , "),e("a",{href:"Pdfs/LinAlg/LinAlg4.pdf"},"4"),a(`), Analyse 1
          (`),e("a",{href:"Pdfs/Ana1Franz/Cours de soutien Eyana 29.9.2023.pdf"},"1"),a(","),e("a",{href:"Pdfs/Ana1Franz/Soutien Edwin 2.8.2022.pdf"},"2"),a(", "),e("a",{href:"Pdfs/Ana1Franz/Soutien Edwin 23.7.2022.pdf"},"3"),a(`,
          `),e("a",{href:"Pdfs/Ana1Franz/Soutien Edwin 30.7.2022.pdf"},"4"),a(", "),e("a",{href:"Pdfs/Ana1/Ana4.pdf"},"4"),a(`),
          Analyse 2 (`),e("a",{href:"Pdfs/Ana2/ana21.pdf"},"1"),a(","),e("a",{href:"Pdfs/Ana2/ana22.pdf"},"2"),a(`,
          `),e("a",{href:"Pdfs/Ana2/ana23.pdf"},"3"),a(", "),e("a",{href:"Pdfs/Ana2/ana24.pdf"},"4"),a(", "),e("a",{href:"Pdfs/Ana2/ana25.pdf"},"5"),a(`),
          Teoría de la medida (`),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 12.1.2024.pdf"},"1"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 2.1.2024.pdf"},"2"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 15.12.2023.pdf"},"3"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leiticia 4.1.2023.pdf"},"4"),a(","),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leiticia 5.1.2023.pdf"},"5"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 13.1.2024.pdf"},"6"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 14.1.2024.pdf"},"7"),a(". "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 6.1.2023.pdf"},"8"),a("), Numérique 1+2 ("),e("a",{href:"Pdfs/Numerik/Numerik1.pdf"},"1"),a(", "),e("a",{href:"Pdfs/Numerik/Numerik2.pdf"},"2"),a(", "),e("a",{href:"Pdfs/Numerik/Numerik3.pdf"},"3"),a(", "),e("a",{href:"Pdfs/Numerik/Numerik4.pdf"},"4"),a(`),
          Estocástico (
          `),e("a",{href:"Pdfs/ProbaFranz/Soutien Edwin 8.7.2022.pdf"},"1"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 2.1.2024.pdf"},"2"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 15.12.2023.pdf"},"3"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leiticia 4.1.2023.pdf"},"4"),a(","),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leiticia 5.1.2023.pdf"},"5"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 13.1.2024.pdf"},"6"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 14.1.2024.pdf"},"7"),a(". "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 6.1.2023.pdf"},"8"),a("), Analyse Complexe 1+2 ("),e("a",{href:"Pdfs/Funktionentheorie/FT1.pdf"},"1"),a(", "),e("a",{href:"Pdfs/Funktionentheorie/FT2.pdf"},"2"),a(" ), Ecuaciónes diferenciales ("),e("a",{href:"Pdfs/DiffglenFranz/Cours de soutien Melina 11.11.2023.pdf"},"1"),a(","),e("a",{href:"Pdfs/DiffglenFranz/Soutien Edwin 30.7.2022.pdf"},"2"),a(`,
          `),e("a",{href:"Pdfs/Diffglen/ODE2.pdf"},"3"),a(", "),e("a",{href:"Pdfs/Diffglen/ODE3.pdf"},"4"),a(", "),e("a",{href:"Pdfs/Diffglen/ODE4.pdf"},"4"),a(", "),e("a",{href:"Pdfs/Diffglen/ODE5.pdf"},"5"),a("), Ecuaciónes en derivadas parciales ("),e("a",{href:"Pdfs/PartielleDGLs/Nachhilfe Eren 22.2.2022.pdf"},"1"),a(", "),e("a",{href:"Pdfs/PartielleDGLs/Nachhilfe Guo 28.8.2022.pdf"},"2"),a(` ),
          Teoría de la probabilidad ( `),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 12.1.2024.pdf"},"1"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 2.1.2024.pdf"},"2"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Camille 15.12.2023.pdf"},"3"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leiticia 4.1.2023.pdf"},"4"),a(","),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leiticia 5.1.2023.pdf"},"5"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 13.1.2024.pdf"},"6"),a(", "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 14.1.2024.pdf"},"7"),a(". "),e("a",{href:"Pdfs/ProbaFranz/Cours de soutien Leticia 6.1.2023.pdf"},"8"),a(`),
          Álgebra (`),e("a",{href:"Pdfs/Algebra/Algebra1.pdf"},"1"),a(", "),e("a",{href:"Pdfs/Algebra/Algebra2.pdf"},"2"),a(", "),e("a",{href:"Pdfs/Algebra/Algebra3.pdf"},"3"),a(", "),e("a",{href:"Pdfs/Algebra/Algebra4.pdf"},"4"),a(", "),e("a",{href:"Pdfs/Algebra/Algebra5.pdf"},"5"),a(", "),e("a",{href:"Pdfs/Algebra/Algebra6.pdf"},"6"),a("), Lógica ("),e("a",{href:"Pdfs/LogikFranz/Soutien Edwin 2.8.2022.pdf"},"1"),a(", "),e("a",{href:"Pdfs/Logik/Logik2.pdf"},"2"),a(", "),e("a",{href:"Pdfs/Logik/Logik3.pdf"},"3"),a(", "),e("a",{href:"Pdfs/Logik/Logik4.pdf"},"4"),a("), Optimización ("),e("a",{href:"Pdfs/Optimierung/Optimierung1.pdf"},"1"),a(","),e("a",{href:"Pdfs/Optimierung/Optimierung2.pdf"},"2"),a(`), Procesos estocásticos, Estadística
          (`),e("a",{href:"Pdfs/Statistik/Statistik1.pdf"},"1"),a(`,
          `),e("a",{href:"Pdfs/Statistik/Statistik2.pdf"},"2"),a(", "),e("a",{href:"Pdfs/Statistik/Statistik3.pdf"},"3"),a(", "),e("a",{href:"Pdfs/Statistik/Statistik4.pdf"},"4"),a("), Teoría de grafos ("),e("a",{href:"Pdfs/Graphentheorie/GT1.pdf"},"1"),a("), Geometría ("),e("a",{href:"Pdfs/Geometrie/Geo1.pdf"},"1"),a(`)
        `)])])],-1)])]),_:1}))}}),g=i({__name:"InfoUni",setup(l){return(d,s)=>(t(),n(r,{id:"infouni",titel:"Informática"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/infouni2francais.jpg",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,"¿Tienes problemas con la gramática de la informática teórica? Puedo ayudarte."),a(),e("p",null,[a(`
          Aquí hay una lista de temas en los que tengo conocimientos:
          Lenguajes formales, Teoría de la complejidad computacional (`),e("a",{href:"FormaleSprachenFranz/Soutien Edwin 9.8.2022 besser.pdf"},"1"),a(","),e("a",{href:"Pdfs/FormaleSprachen/FS2.pdf"},"2"),a(" , "),e("a",{href:"Pdfs/FormaleSprachen/FS3.pdf"},"3"),a(", "),e("a",{href:"Pdfs/FormaleSprachen/FS4.pdf"},"4"),a(`,
          `),e("a",{href:"Pdfs/PumpingEigenschaft.pdf"},"5"),a("), Ciencia computacional teórica ("),e("a",{href:"Pdfs/TheoretischeInformatik/TH1.pdf"},"1"),a(", "),e("a",{href:"Pdfs/TheoretischeInformatik/TH2.pdf"},"2"),a(", "),e("a",{href:"Pdfs/TheoretischeInformatik/TH3.pdf"},"3"),a(", "),e("a",{href:"Pdfs/TheoretischeInformatik/TH4.pdf"},"4"),a(", "),e("a",{href:"Pdfs/TheoretischeInformatik/TH5.pdf"},"5"),a(`), Algoritmos e Estructuras de datos
          (`),e("a",{href:"Pdfs/Ana1Franz/Cours de soutien Eyana 29.9.2023.pdf"},"1"),a(", "),e("a",{href:"Pdfs/AlgoDat/AlgoDat1.pdf"},"2"),a(", "),e("a",{href:"Pdfs/AlgoDat/AlgoDat2.pdf"},"3"),a(", "),e("a",{href:"Pdfs/AlgoDat/AlgoDat3.pdf"},"4"),a(", "),e("a",{href:"Pdfs/AlgoDat/AlgoDat4.pdf"},"5"),a(", "),e("a",{href:"Pdfs/AlgoDat/AlgoDat5.pdf"},"6"),a(", "),e("a",{href:"Pdfs/AlgoDat/AlgoDat6.pdf"},"7"),a(`),
          Teoría de la computabilidad ( `),e("a",{href:"Pdfs/Komplexitaetstheorie/Komplexitaet1.pdf"},"1"),a(`),
          Introducción a la programación (`),e("a",{href:"Pdfs/Programmierung/ListUndStack.pdf"},"1"),a(","),e("a",{href:"Pdfs/LineareListe.pdf"},"2"),a(", "),e("a",{href:"Pdfs/Programmierung/Programmierung2.pdf"},"3"),a(`),
          Programación funcional con Haskell (`),e("a",{href:"Pdfs/Haskell/Nachhilfe Marvin 15.6.2022.pdf"},"1"),a(","),e("a",{href:"Pdfs/Haskell/Nachhilfe Marvin 17.6.2022.pdf"},"2"),a(", "),e("a",{href:"Pdfs/Haskell/Nachhilfe Nissa 2.7.2022.pdf"},"3"),a("), Matemática discreta ("),e("a",{href:"Pdfs/DiskreteStrukturen/Diskret1.pdf"},"1"),a(", "),e("a",{href:"Pdfs/DiskreteStrukturen/Diskret2.pdf"},"2"),a(", "),e("a",{href:"Pdfs/DiskreteStrukturen/Diskret3.pdf"},"3"),a(", "),e("a",{href:"Pdfs/DiskreteStrukturen/Diskret4.pdf"},"4"),a("), Lógica ("),e("a",{href:"Pdfs/Logik/Logik5.pdf"},"1"),a(`),
          Informatique Graphique (`),e("a",{href:"Pdfs/Computergraphik/graphik1.png"},"1"),a(`,
          `),e("a",{href:"Pdfs/Computergraphik/graphik2.png"},"2"),a(`)
        `)]),e("p")])],-1),a(),e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/programming.png",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,[a(`
          También puedo ayudarte con la programación (Java, C/C++, C#, Haskell, R, Python, Prolog, Rust, OCaml)
          o con programación web (Html, CSS, JavaScript, PHP,SQL, NodeJS, VueJS, AngularJS, MongoDB, Java Servlets/JSP).
          Utilizaríamos Eclipse, IntelliJ o VisualStudio como entorno de desarrollo con el `),e("a",{href:"https://plugins.jetbrains.com/plugin/14225-codetogether"},"CodeTogether-Plugin"),a(` ,
          que permite la programación en pares.

        `)])])],-1)])]),_:1}))}}),P=i({__name:"PhysikUni",setup(l){return(d,s)=>(t(),n(r,{id:"physikuni",titel:"Física"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/physikuni.png",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,"Como buen físico, el número de errores de signo debe ser siempre par. Todo lo demás te lo puedo explicar."),a(),e("p",null,[a(`
          En un curso privado, podemos hacer: Física experimental, es decir
          Mecánica (`),e("a",{href:"Pdfs/Mechanik/M1.pdf"},"1"),a(", "),e("a",{href:"Pdfs/Mechanik/M2.pdf"},"2"),a(", "),e("a",{href:"Pdfs/Mechanik/M3.pdf"},"3"),a(", "),e("a",{href:"Pdfs/Mechanik/Nachhilfe Ksenija 1.12.2021.pdf"},"4"),a(", "),e("a",{href:"Pdfs/Mechanik/Nachhilfe Steven 9.5.2021.pdf"},"5"),a(`),
          Electromagnetismo (`),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Nick 5.5.2021.pdf"},"1"),a(`,
          `),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Suganya 21.9.2021.pdf"},"2"),a(`,
          `),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Suganya 22.9.2021.pdf"},"3"),a(`,
          `),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Nick 5.7.2021.pdf"},"4"),a(`,
          `),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Shir 4.7.2021.pdf"},"5"),a(`,
          `),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Shir 11.7.2021.pdf"},"6"),a(`,
          `),e("a",{href:"Pdfs/Elektromagnetismus/Nachhilfe Shir 16.6.2021.pdf"},"7"),a(`),
          Ondas electromagneticos e Óptica (`),e("a",{href:"Pdfs/WellenUndOptik/Optik1.pdf"},"1"),a(","),e("a",{href:"Pdfs/WellenUndOptik/Optik2.pdf"},"2"),a(", "),e("a",{href:"Pdfs/WellenUndOptik/Optik3.pdf"},"3"),a(", "),e("a",{href:"Pdfs/WellenUndOptik/Optik4.pdf"},"4"),a(","),e("a",{href:"Pdfs/WellenUndOptik/Optik5.pdf"},"5"),a(","),e("a",{href:"Pdfs/WellenUndOptik/Nachhilfe Tuba 2.12.2021.pdf"},"6"),a(`),
          Termodinámica/Física estadística (`),e("a",{href:"Pdfs/ThermodynamikFranz/Cours de soutien Thomas 16.9.2023.pdf"},"1"),a(","),e("a",{href:"Pdfs/ThermodynamikFranz/Cours de soutien Thomas 17.9.2023.pdf"},"2"),a(","),e("a",{href:"Pdfs/ThermodynamikFranz/Cours de soutien Thomas 24.9.2023.pdf"},"3"),a(`), Teoría de la relatividad, Física atómica, Física nuclear y
          Física del estado sólido (`),e("a",{href:"Pdfs/Festkörperphysik/Nachhilfe Suganya 20.9.2021.pdf"},"1"),a(`)

          y `),e("br"),a(` Física teórica , es decir Mécanica teórica,
          Electrodinámica (`),e("a",{href:"Pdfs/Elektrodynamik/ED1.pdf"},"1"),a(", "),e("a",{href:"Pdfs/Elektrodynamik/Nachhilfe Nick 31.5.2021.pdf"},"2"),a(`),
          Mecánica cuántica (`),e("a",{href:"Pdfs/QM/QM1.pdf"},"1"),a(", "),e("a",{href:"Pdfs/QM/QM2.pdf"},"2"),a(", "),e("a",{href:"Pdfs/QM/QM3.pdf"},"3"),a(", "),e("a",{href:"Pdfs/QM/QM4.pdf"},"4"),a(`) y Termodinámica
          (`),e("a",{href:"Pdfs/Thermodynamik/TD1.pdf"},"1"),a(", "),e("a",{href:"Pdfs/Thermodynamik/TD2.pdf"},"2"),a(`) y
          `),e("br"),a(" para los ingenieros: Mecánica aplicada ("),e("a",{href:"Pdfs/TechnischeMechanik/Nachhilfe Balbine 15.12.2021.pdf"},"1"),a(`,
          `),e("a",{href:"Pdfs/TechnischeMechanik/Nachhilfe Hicham 31.12.2021.pdf"},"2"),a(`)
          y Mecánica de fluidos (`),e("a",{href:"Pdfs/Strömungslehre/SL1.pdf"},"1"),a(`,
          `),e("a",{href:"Pdfs/Strömungslehre/Nachhilfe Gwendolin 30.10.2021.pdf"},"2"),a(", "),e("a",{href:"Pdfs/Strömungslehre/Nachhilfe Wei Liu 27.3.2022.pdf"},"3"),a(`)

        `)])])],-1)])]),_:1}))}}),b=i({__name:"Ingenieurwesen",setup(l){return(d,s)=>(t(),n(r,{id:"ingenieurwesen",titel:"Ingeniería"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/ingenieurwesen.png",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,'Cuando estuve en Estados Unidos hace unos años, me di cuenta de que allí se admira la "ingeniería alemana".'),a(),e("p",null,[a(`
          En un curso de apoyo podemos realizar: Mecánica aplicada (`),e("a",{href:"Pdfs/TechnischeMechanik/Nachhilfe Balbine 15.12.2021.pdf"},"1"),a(`,
          `),e("a",{href:"Pdfs/TechnischeMechanik/Nachhilfe Hicham 31.12.2021.pdf"},"2"),a(`), Análisis estructural,
          Ingeniería eléctrica (`),e("a",{href:"Pdfs/Elektrotechnik/Nachhilfe Raphael 26.10.2022.pdf"},"1"),a(", "),e("a",{href:"Pdfs/Elektrotechnik/Nachhilfe Shir 4.7.2021.pdf"},"2"),a(", "),e("a",{href:"Pdfs/Elektrotechnik/Nachhilfe Shir 11.7.2021.pdf"},"3"),a(`)
          y Mecánica de fluidos (`),e("a",{href:"Pdfs/Strömungslehre/SL1.pdf"},"1"),a(`,
          `),e("a",{href:"Pdfs/Strömungslehre/Nachhilfe Gwendolin 30.10.2021.pdf"},"2"),a(`,
          `),e("a",{href:"Pdfs/Strömungslehre/Nachhilfe Wei Liu 27.3.2022.pdf"},"3"),a(`),
          Ingeniería de control, Ingeniería de telecomunicaciones, Ingeniería de radiofrecuencia

        `)])])],-1)])]),_:1}))}}),_=i({__name:"MatheSchule",setup(l){return(d,s)=>(t(),n(r,{id:"matheschule",titel:"Matemáticas"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/matheschule.png",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`En matemáticas, lo único que hay que hacer es encontrar la ecuación correcta y
          luego resolverla sin cometer errores en el cálculo.

        `)])],-1)])]),_:1}))}}),y=i({__name:"PhysikSchule",setup(l){return(d,s)=>(t(),n(r,{id:"physikschule",titel:"Física"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/physiqueecole.jpg",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,"No le tengas miedo a la física. Sólo con la fórmula F=ma ya llegarás bastante lejos.")])],-1)])]),_:1}))}}),v=i({__name:"InfoSchule",setup(l){return(d,s)=>(t(),n(r,{id:"infoschule",titel:"Informática"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/infoschule.jpg",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`Una computadora no puede sentir ni pensar por sí misma, pero puede resolver cosas muy rápidamente.
          Por eso es útil en la vida saber que el ratón del ordenador no muerde.`)])],-1)])]),_:1}))}}),k=i({__name:"Deutsch",setup(l){return(d,s)=>(t(),n(r,{id:"deutsch",titel:"Alemán"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/deutsch.png",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`Deutsche Sprache = Schwere Sprache. Ich kann dir erklären, wie du die ä's, ö's und ü's richtig verteilen musst,
          damit man dich noch besser versteht.
        `),a(),e("p",null,`
        Esto significa: Puedo explicarte cómo debes distribuir todas las ä, ö y ü para que te entendamos mejor.
        `)])],-1)])]),_:1}))}}),S=i({__name:"Englisch",setup(l){return(d,s)=>(t(),n(r,{id:"englisch",titel:"Inglés"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/FlyerConditionalSentences.jpg",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`¿Tienes la nariz llena de inglés? ¡No digas eso!
          En lugar de eso, di "Estoy harto del inglés"
          y ven a mi casa para recibir una clase privada.`)])],-1)])]),_:1}))}}),z={class:"row"},F={class:"col-lg-8 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},C={id:"nutritionquiz"},E=i({__name:"Ernaehrung",setup(l){return(d,s)=>(t(),n(r,{id:"ernaehrung",titel:"Nutrición"},{default:o(()=>[e("div",z,[e("div",F,[e("div",C,[f(u,{quiz:"nutrition",lg:"fr"})])]),s[0]||(s[0]=a()),s[1]||(s[1]=e("div",{class:"col-lg-3 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`Mis alumnos a menudo se enferman de repente, generalmente 5 minutos antes de una lección privada.
           A la derecha hay un pequeño cuestionario sobre alimentación saludable.
        `)],-1))])]),_:1}))}}),M={class:"row"},A={class:"col-lg-8 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},w={id:"conciousness"},N=i({__name:"Bewusstsein",setup(l){return(d,s)=>(t(),n(r,{id:"bewusstsein",titel:"Consciencia"},{default:o(()=>[e("div",M,[e("div",A,[e("div",w,[f(u,{quiz:"consciousness",lg:"fr"})])]),s[0]||(s[0]=a()),s[1]||(s[1]=e("div",{class:"col-lg-4 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,"La consciencia debería ser una asignatura principal en la escuela pero no lo es.")],-1))])]),_:1}))}}),T={class:"row"},L={class:"col-lg-8 order-2 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},D=i({__name:"Schach",setup(l){return(d,s)=>(t(),n(r,{id:"schach",titel:"Ajedrez"},{default:o(()=>[e("div",T,[e("div",L,[f(p,{lg:"de"})]),s[0]||(s[0]=a()),s[1]||(s[1]=e("div",{class:"col-lg-4 pt-4 pt-lg-0 order-1 order-lg-1 content"},[e("p",null,`El ajedrez es bueno para la capacidad de imaginación.
          Los problemas de la derecha datan de una época en la que todavía enseñaba ajedrez en la escuela primaria.`)],-1))])]),_:1}))}}),q=i({__name:"WebsitenUndFlyer",setup(l){return(d,s)=>(t(),n(r,{id:"websitenundflyer",titel:"Páginas web"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/WebsiteProgrammierungFlyer3.png",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`¿Necesitas ayuda con un proyecto de programación web para tus estudios?
          ¿O quieres aprender Programación Web para crear tu propio sitio web basado en HTML, CSS y JavaScript
          y necesitas ayuda para empezar? Definitivamente puedo ayudarte con mis conocimientos
          y experiencia en las siguientes áreas:
        `),a(),e("p"),e("ul",null,[e("li",null,"Programación de sitios web estáticos/frontend (Html, CSS, JavaScript, Bootstrap, VueJS, AngularJS)"),a(),e("li",null,"Programación de sitios web dinámicos (PHP, NodeJS, Java Servlets /JSP)"),a(),e("li",null,"Base de datos (MySQL, MongoDB)"),a(),e("li",null,"Responsive Web-Design"),a(),e("li",null,"Edición de imágenes (avec GIMP)"),a(),e("li",null,"Hosting (por ejemplo, gratuito en GitHub o Netlify )"),a(),e("li",null,"Legal"),a(),e("li",null,"Traducción (en alemán e inglés)")]),a(),e("p")])],-1)])]),_:1}))}}),x=i({__name:"Preise",setup(l){return(d,s)=>(t(),n(r,{id:"preise",titel:"Precios, citas y pagos"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-12 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("h3",null,"Precio"),a(),e("p",null,"4 * 20 euros por 4*60 minutos para ti solo, o para ti y un amigo."),a(),e("p",null,"25 euros por una sola clase"),a(),e("p",null,[a("Si la clase dura más de 60 minutos, hay que aplicar la siguiente formula:"),e("br"),a(`

    Precio= Tiempo/(60 minutos) * (precios por 60 minutos)`)]),a(),e("p",null,`Puedes obtener el precio más barato con un paquete de 4*60 minutos si tienes suficientes ejercicios interesantes.
                  Para aprovechar el paquete, hay que tomar por lo menos una hora de clase por semana.
                  Estoy disponible todos los días de la semana de las 8h a las 21h y puedo ayudarte en varias asignaturas.
                  !!!!!Ojo!!!!!! Si, por cualquier razón, no puedes o crees que no necesitas tomar una clase durante una semana,
                  no se devolverá el dinero. Sino, las siguientes condiciones de cancelación se aplican a cada una de las 4 citas
                  del paquete.
    `),a(),e("h3",null,"Condiciones de citas, pago y cancelación"),a(`
                Solo acepto la primera hora de clase por email. Entonces estoy disponible vía Skype. Por favor, sigue el siguiente proceso de reserva de cita:

                `),e("ol",null,[e("li",null,"Me envías tus ejercicios y tus apuntes del curso."),a(),e("li",null,`Si conozco este tipo de ejercicios, te diré que puedes realizar el pago vía Paypal con
                    la opción “Envía dinero a tus seres queridos”* o transferencia bancaria + Captura de pantalla.
                    En el título de la transferencia, escribe tu nombre y tus preferencias de cita,
                    por ejemplo algo como "Se desea tutoría de matemáticas de Elif el miércoles 11.1 de 3 p.m. a 11 p.m. o el sábado 12.1
                     entre las 8 a.m. y las 12 p.m. o todo el día domingo".
                  `),e("li",null,`Después de recibir el pago,
                    te daré una confirmación de cita según tus preferencias (si es posible)
                    o te ofreceré 2-3 citas para los próximos días.`),a(),e("li",null,"Espero conocerte pronto y puedes enviarme cualquier ejercicio o nota de lección faltante o adicional.")]),a(),e("p",null,[e("span",{style:{"font-weight":"bold"}},"¡¡¡Por favor ten en cuenta las condiciones de cancelación, no se admiten reprogramaciones de citas!!!"),a(`
                  En caso de cancelación de la cita (en cualquier momento antes de la clase)
                  o problemas técnicos (por ejemplo, conexión a Internet inestable,
                  imposibilidad de usar Skype, Zoom, micrófono o parlantes) o después de un retraso de más de 10 minutos de tu parte,
                  el dinero aún debe pagarse y ya no estoy obligado a esperar.
                `)]),a(),e("p",null,"En caso de cancelación o corte de Internet por mi parte, recibirás otra cita o te devolveremos tu dinero."),a(),e("p",null,"*Sin la opción “Envía dinero a tus seres queridos” hay una comisión de 2 euros por Paypal.")])],-1)])]),_:1}))}}),j=i({__name:"MethodeEnseignement",setup(l){return(d,s)=>(t(),n(r,{id:"methodeenseignement",titel:"Método de enseñanza"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/owllehrer.png",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,`
          Entre los ejercicios que me enviaste escogemos los mejores.
          Para explicarlo, uso diagramas, palabras, fórmulas, reglas generales y teoremas (de tus apuntes de clase),
          colores, ejemplos y finalmente, el ejercicio se explica por sí solo a través de su solución e interpretación en
          contexto y validación.
        `)])],-1)])]),_:1}))}}),O=i({__name:"Online",setup(l){return(d,s)=>(t(),n(r,{id:"online",titel:"Clases en línea"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/miroapp.png",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("p",null,[a(`
            Para clases privadas online, uso Teams o Zoom. Si prefieres uno u otro puedes mencionarlo. Además, utilizo la `),e("a",{href:"https://miro.com/online-whiteboard/"},"Miro-Online-Whiteboard"),a(`,
             con la que podemos escribir algo juntos. Aquí se muestra un ejemplo de una pizarra llena:
             Ejemplo de una `),e("a",{href:"Pdfs/Beispielwhiteboard.pdf"},"pizarra llena")])])],-1)])]),_:1}))}}),I=i({__name:"UeberMich",setup(l){return(d,s)=>(t(),n(r,{id:"uebermich",titel:"Acerca de mí"},{default:o(()=>[...s[0]||(s[0]=[e("div",{class:"row"},[e("div",{class:"col-lg-6 order-1 order-lg-2","data-aos":"fade-left","data-aos-delay":"100"},[e("img",{src:"assets/img/me3.jpg",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"},[e("ul",{style:{"list-style-type":"disc"}},[e("li",null,"Máster en matemáticas y ciencias de la computación en la  Universidad LMU de Múnich con honores"),a(),e("li",null,"1er Exámen de estado de docencia y matemáticas en bachillerato."),a(),e("li",null,">5 años de tutoría de numerosas matemáticas y física en la Universidad LMU de Múnich"),a(),e("li",null,"Diploma de bachillerato en inglés y francés."),a(),e("li",null,"6 meses de experiencia en el instituto de Gröbenzell y Olching de Matemáticas y Física"),a(),e("li",null,"Tutor a tiempo completo desde Octubre del 2020"),a(),e("li",null,"1 año de experiencia profesional como Desarrollador de Software"),a(),e("li",null,"Formación de profesor de yoga en Sivananda Yoga en 2018")])])],-1),a(),e("div",{class:"row",style:{"margin-top":"10px"}},[e("div",{class:"col-lg-2 order-1 order-lg-1","data-aos":"fade-right","data-aos-delay":"100"},[e("img",{src:"assets/img/yoga/kopfstand2.jpg",class:"img-fluid",alt:""})]),a(),e("div",{class:"col-lg-10 pt-4 pt-lg-0 order-2 order-lg-2 content"},[e("p",null,[a(`Nací en 1993, hijo de un ingeniero eléctrico y una nutricionista.
           Mi abuelo también influyó profundamente, pues vivía a partir de verduras de su huerto y a partir de dientes
           de león para poder sustentar el estudio de sus nietos.`),e("br"),a(`
           Aprendí mucho también de mis tíos, quienes, como profesores de historia y lengua,
           siempre tenían un montón de historias divertidas que contar.`),e("br"),a(`
           Me interesa todo lo relacionado con las matemáticas, la ciencia, la tecnología, los idiomas y la psicología,
           esta última para el deleite de mi psiquiatra,
           que se gana la vida escuchándome.`),e("br"),a(`
           Para mantener la mente siempre fresca y preparada para aprender cosas nuevas e interesantes,
           doy muchos paseos por el bosque, practico yoga y deporte, te lo recomiendo también,
           sobre todo antes de un examen.
        `)])])],-1)])]),_:1}))}}),G={logo:"Pregúntale a Florian!",knopf:"Escríbeme un mensaje",heroBild:"assets/img/ingenieurwesenSpanischMitKopf.png",flaggen:c.flaggen,menue:[{titel:"Universidad",ziel:"#matheuni",eintraege:[{titel:"Matemáticas",ziel:"#matheuni"},{titel:"Informática",ziel:"#infouni"},{titel:"Física",ziel:"#physikuni"},{titel:"Ingeniería",ziel:"#ingenieurwesen"}]},{titel:"Colegio",ziel:"#matheschule",eintraege:[{titel:"Matemáticas",ziel:"#matheschule"},{titel:"Física",ziel:"#physikschule"},{titel:"Informatíca",ziel:"#infoschule"},{titel:"Alemán",ziel:"#deutsch"},{titel:"Inglés",ziel:"#englisch"}]},{titel:"Vida",ziel:"#ernaehrung",eintraege:[{titel:"Nutrición",ziel:"#ernaehrung"},{titel:"Consciencia",ziel:"#bewusstsein"},{titel:"Ajedrez",ziel:"#schach"},{titel:"Páginas web",ziel:"#websitenundflyer"}]},{titel:"Precio y otra información",ziel:"#preise",eintraege:[{titel:"Precios y otra información",ziel:"#preise"},{titel:"Método de enseñanza",ziel:"#methodeenseignement"},{titel:"Clases en grupo",ziel:"#tutorium"},{titel:"Clases privadas en línea",ziel:"#online"}]},{titel:"Acerca de mí",ziel:"#uebermich",eintraege:[]}],kontakt:{karteHoehe:"200px",karte:c.karte,adresse:"Dirección:",email:"Dirección de correo electrónico:",strasse:c.strasse,ort:c.ort,mailadresse:c.mailadresse,absatz:"Puedes utilizar este formulario para contactarme, pero es mejor si me contactas por correo electrónico y me envías suficientes ejercicios para que podamos discutir durante una lección privada.",formular:{action:"https://api.web3forms.com/submit",accessKey:"aaa027db-e72d-41d2-9b3b-7603e4908475",weiterleitung:"https://florianingerl.github.io/formsubmissionconfirmation.html",botcheck:!0,name:"Tu nombre",mail:"Tu email",betreff:"Asunto",nachricht:"Mensaje",knopf:"Enviar mensaje"}},fuss:{telefon:"Teléfono:",telefonnummer:c.telefonnummer,mailadresse:c.mailadresse,sozial:!0},schach:"de",abschnitte:[m,h,g,P,b,_,y,v,k,S,E,N,D,q,x,j,O,I]};export{G as default};
